import type { News } from "../types/News";

export const news: News[] = [
  { id:1, title:"Nova tecnologia em IA revoluciona setor", date:"2025-09-24",
    content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.",
    image:"https://picsum.photos/800/400?1", categories:["Tech","AI"],
    comments:[{id:1,name:"Fulano",text:"Muito interessante!",date:"2025-09-24"}] },
    { id:2, title:"Nova tecnologia em IA revoluciona setor", date:"2025-09-24",
    content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.",
    image:"https://picsum.photos/800/400?1", categories:["Tech","AI"],
    comments:[{id:1,name:"Fulano",text:"Muito interessante!",date:"2025-09-24"}] },
    { id:3, title:"Nova tecnologia em IA revoluciona setor", date:"2025-09-24",
    content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.",
    image:"https://picsum.photos/800/400?1", categories:["Tech","AI"],
    comments:[{id:1,name:"Fulano",text:"Muito interessante!",date:"2025-09-24"}] },
    { id:4, title:"Nova tecnologia em IA revoluciona setor", date:"2025-09-24",
    content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.",
    image:"https://picsum.photos/800/400?1", categories:["Tech","AI"],
    comments:[{id:1,name:"Fulano",text:"Muito interessante!",date:"2025-09-24"}] },
    { id:5, title:"Nova tecnologia em IA revoluciona setor", date:"2025-09-24",
    content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.",
    image:"https://picsum.photos/800/400?1", categories:["Tech","AI"],
    comments:[{id:1,name:"Fulano",text:"Muito interessante!",date:"2025-09-24"}] },
    { id:6, title:"Nova tecnologia em IA revoluciona setor", date:"2025-09-24",
    content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.",
    image:"https://picsum.photos/800/400?1", categories:["Tech","AI"],
    comments:[{id:1,name:"Fulano",text:"Muito interessante!",date:"2025-09-24"}] },
    { id:7, title:"Nova tecnologia em IA revoluciona setor", date:"2025-09-24",
    content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.",
    image:"https://picsum.photos/800/400?1", categories:["Tech","AI"],
    comments:[{id:1,name:"Fulano",text:"Muito interessante!",date:"2025-09-24"}] },
    { id:8, title:"Nova tecnologia em IA revoluciona setor", date:"2025-09-24",
    content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.",
    image:"https://picsum.photos/800/400?1", categories:["Tech","AI"],
    comments:[{id:1,name:"Fulano",text:"Muito interessante!",date:"2025-09-24"}] },
    { id:9, title:"Nova tecnologia em IA revoluciona setor", date:"2025-09-24",
    content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.",
    image:"https://picsum.photos/800/400?1", categories:["Tech","AI"],
    comments:[{id:1,name:"Fulano",text:"Muito interessante!",date:"2025-09-24"}] },
  { id:10, title:"Mercado financeiro em alta", date:"2025-09-20",
    content:"Curabitur blandit tempus porttitor. Praesent commodo cursus magna, vel scelerisque nisl.",
    image:"https://picsum.photos/800/400?2", categories:["Economia"],
    comments:[{id:2,name:"Ciclano",text:"Notícia relevante.",date:"2025-09-21"}] }
  // Adicione até ter pelo menos 10 itens
];
